### PR TITLE
Fix file explorer

### PR DESCRIPTION
**Pull request by kaleemullah786**
kindly review the responsiveness of file explorer

### CODE REVIEW

**Comment by amirihusayn** [comment]
If it possible pull our main branch with rebase option; Because if I do rebase your commit sings will be mine. So on your `fix-file-explorer` branch run :  
```
git pull https://github.com/ceituut/ceituut.github.io.git --rebase
```
Then push with force option :  
```
git push --force
```

**Comment by amirihusayn** [comment]
Also revert the `package.json` and `package.lock.json` changes.

**Comment by kaleemullah786** [comment]
> If it possible pull our main branch with rebase option; Because if I do rebase your commit sings will be mine. So on your `fix-file-explorer` branch run :  
> ```
> git pull https://github.com/ceituut/ceituut.github.io.git --rebase
> ```
> Then push with force option :  
> ```
> git push --force
> ```
> 

I've did this

**Comment by amirihusayn** [comment]
Thanks @kaleemullah786. I really appreciate for your helps and supports, and a lot of things learned from You. I continue work on this feature because it have some works to do. Then I will merge your changes and close this issue. Thanks again !

**Comment by kaleemullah786** [comment]
Alright. It's a great experience working with you, thanks for this kindness and support.

**Pull request merged**
